### ISSUE TITLE
"TypeError: ADC0_read.toFixed is not a function"

### ISSUE THREAD

**Issue by Barabba11** [meeki007/node-red-contrib-ads1x15-raspi#3]
Hi, time by time this function, which is directly connected to your node, give me these errors. It may occour (not always) after a "light" deply (only for changed nodes, whiich arent' anything around your module), or at random time. Maybe 2/3 times in a day. What can it be? Maybe in that moment it doesn't output a number?
I've a Pi3B running latest rasbian, nodes and NR 1.3.5

`[{"id":"3249745c.844bac","type":"inject","z":"cc2c1666.3d904","name":"Clock 1s","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"1","crontab":"","once":true,"onceDelay":0.1,"topic":"","payload":" ","payloadType":"str","x":220,"y":120,"wires":[["fdf9b950.b478e8"]]},{"id":"fdf9b950.b478e8","type":"ads1x15_i2c","z":"cc2c1666.3d904","property":"payload","name":"","i2c_device_number":1,"chip":"0x01","i2c_address":"0x4A","inputsForChannel":"singleEnded","singleEndedChannel0":true,"singleEndedChannel1":true,"singleEndedChannel2":true,"singleEndedChannel3":true,"differentialChannel0_1":true,"differentialChannel0_3":false,"differentialChannel1_3":false,"differentialChannel2_3":true,"samplesPerSecond0":"920","samplesPerSecond1":"8","progGainAmp":"4096","x":450,"y":120,"wires":[["f6d2ed31.8dec6"]]},{"id":"f6d2ed31.8dec6","type":"function","z":"cc2c1666.3d904","name":"Estrapola i valori ADC","func":"let ADC0_read = msg.payload[\"/dev/i2c-1\"].ads1115[\"0x4A\"].singleEnded.channel_0.miliVolts;\nvar ADC0=ADC0_read.toFixed(3); global.set('ADC0',ADC0);\nlet ADC1_read = msg.payload[\"/dev/i2c-1\"].ads1115[\"0x4A\"].singleEnded.channel_1.miliVolts;\nvar ADC1=ADC1_read.toFixed(3); global.set('ADC1',ADC1);\nlet ADC2_read = msg.payload[\"/dev/i2c-1\"].ads1115[\"0x4A\"].singleEnded.channel_2.miliVolts;\nvar ADC2=ADC2_read.toFixed(3); global.set('ADC2',ADC2);\nlet ADC3_read = msg.payload[\"/dev/i2c-1\"].ads1115[\"0x4A\"].singleEnded.channel_3.miliVolts;\nvar ADC3=ADC3_read.toFixed(3); global.set('ADC3',ADC3);\nnode.status({fill:\"blue\",shape:\"dot\",text:ADC0+\" ! \"+ADC1+\" ! \"+ADC2+\" ! \"+ADC3});\n\nmsg1 = {ADC0:ADC0,ADC1:ADC1,ADC2:ADC2,ADC3:ADC3}; \nreturn msg1;\n","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":660,"y":60,"wires":[["6774e0a9.e62468"]]}]
`

**Comment by meeki007** [comment]
correct! sometimes it will not be a number but a string
could be "ADC is busy..."

no I can not fix this as its in the depend i use. see line 475 https://github.com/felixdrp/ads1x15/blob/main/index.js#L475

**Comment by Barabba11** [comment]
thanks, I've filtered then numbers only and discard other messages. I'm running it and for now I don't have errors
