### ISSUE TITLE
Channel mismatch

### ISSUE THREAD

**Issue by alexander-thiesen** [meeki007/node-red-contrib-ads1x15-raspi#6]
Hello meeki007,

we have a problem with the communication to our ads1115 chip. 
When we read out the chip using your module the channels get messed up. That means that when we read out channel 2 and 3 the output of channel 2 has sometimes the value of channel 3, vice versa. 
For easy demonstration purposes we set the input voltages of the ADC to 1, 2, 3, 4 V respectively. 
We ask for the values every 200 ms. Input is single ended. Until now we used 128 Samples/sec.
Do you have a idea where the source of this problem might be and how to solve it?

Thank you in advance

Alexander Thiesen

![image](https://github.com/meeki007/node-red-contrib-ads1x15_i2c/assets/53611602/bc8190db-3e3a-490d-a053-fc4bc7649175)

Error filter function:

```
var input2 = msg.payload["/dev/i2c-1"]["ads1115"]["0x48"].singleEnded.channel_3.Volts;
if (input2 >4.2 | input2 < 3.8){
    var date = Date();
    return {payload:(date + "\n" + input2.toString())};
}
```

**Comment by meeki007** [comment]
2 years ago I created this for a client. I'm sorry but I do not have access to a ads1115 chip any longer.
If I ever have a need for this in the future or have a adsX chip in had I will look into issue. 
If you would like to take over the repository let me know and I will transfer it to you so you can update / fix any issues.

**Comment by alexander-thiesen** [comment]
Hello @meeki007 ,
thank you for your quick answer. 
I found a fix for the issue, which was up at the https://github.com/felixdrp/ads1x15 repository. 
So there is no need to take over the repository.

Greetings
